import fs from 'node:fs/promises';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
import {expect,it} from 'vitest';
it('imports and validates a retained copy without an editor, and reports invalid source structurally',async()=>{
 const godot=process.env.GODOT_BIN;if(!godot)throw new Error('GODOT_BIN required');
 const parent=path.resolve('.godot-mcp/cli-test-runs');await fs.mkdir(parent,{recursive:true});const root=await fs.mkdtemp(path.join(parent,'headless-'));
 await fs.writeFile(path.join(root,'project.godot'),'config_version=5\n[application]\nconfig/name="Headless validation fixture"\nrun/main_scene="res://main.tscn"\n');
 await fs.writeFile(path.join(root,'base.gd'),'class_name AuditBase\nextends Node\n');
 await fs.writeFile(path.join(root,'main.gd'),'extends AuditBase\nfunc reload():\n\treturn 42\n');
 await fs.writeFile(path.join(root,'main.tscn'),'[gd_scene load_steps=2 format=3]\n[ext_resource type="Script" path="res://main.gd" id="1"]\n[node name="Main" type="Node"]\nscript = ExtResource("1")\n');
 await fs.mkdir(path.join(root,'.godot-mcp'));await fs.writeFile(path.join(root,'.godot-mcp/config.json'),JSON.stringify({godotBin:godot}));
 const client=new Client({name:'headless-test',version:'1'});
 const transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('packages/cli/dist/index.js'),'start',root,'--bridge-port','0']});
 try{
  await client.connect(transport);
  const valid=await client.callTool({name:'project.validate',arguments:{timeout_ms:60000}});
  expect(valid.isError,JSON.stringify(valid)).not.toBe(true);
  expect(valid.structuredContent).toMatchObject({valid:true,complete:true});
  await expect(fs.stat(path.join(root,'.godot'))).rejects.toMatchObject({code:'ENOENT'});
  await fs.writeFile(path.join(root,'main.gd'),'extends Node\nfunc broken(\n');
  const invalid=await client.callTool({name:'project.validate',arguments:{timeout_ms:60000}});
  expect(invalid.isError,JSON.stringify(invalid)).not.toBe(true);
  expect(invalid.structuredContent).toMatchObject({valid:false,complete:true});
  const report=invalid.structuredContent as any;
  expect(report.diagnostics.some((d:any)=>d.severity==='error')).toBe(true);
  expect(report.files.some((f:any)=>f.path==='res://main.gd'&&!f.valid)).toBe(true);
  expect(JSON.parse(await fs.readFile(path.join(report.artifactPath,'report.json'),'utf8')).valid).toBe(false);
  expect(await fs.readFile(path.join(root,'main.gd'),'utf8')).toContain('func broken(');
  await fs.writeFile(path.join(root,'main.gd'),'extends AuditBase\n');
  await fs.mkdir(path.join(root,'addons/blocker'),{recursive:true});
  await fs.writeFile(path.join(root,'addons/blocker/plugin.cfg'),'[plugin]\nname="Blocker fixture"\ndescription="Validation timeout fixture"\nauthor="test"\nversion="1"\nscript="plugin.gd"\n');
  await fs.writeFile(path.join(root,'addons/blocker/plugin.gd'),'@tool\nextends EditorPlugin\nfunc _enter_tree():\n\tprint("VALIDATION_TIMEOUT_FIXTURE_STARTED")\n\twhile true:\n\t\tpass\n');
  await fs.appendFile(path.join(root,'project.godot'),'\n[editor_plugins]\nenabled=PackedStringArray("res://addons/blocker/plugin.cfg")\n');
  const timeout=await client.callTool({name:'project.validate',arguments:{timeout_ms:5000}});
  expect(timeout.isError).toBe(true);
  expect(timeout.structuredContent).toMatchObject({valid:false,complete:false});
  const timed=timeout.structuredContent as any;
  expect(timed.diagnostics.some((d:any)=>d.code==='PROCESS_TIMEOUT')).toBe(true);
  expect(await fs.readFile(path.join(timed.artifactPath,'import.log'),'utf8')).toContain('VALIDATION_TIMEOUT_FIXTURE_STARTED');
  expect((await client.callTool({name:'session.status',arguments:{}})).isError).not.toBe(true);
  await fs.writeFile(path.join(root,'addons/blocker/plugin.gd'),'@tool\nextends EditorPlugin\nfunc _enter_tree():\n\tvar file=FileAccess.open("res://main.gd",FileAccess.WRITE)\n\tfile.store_string("extends Node\\n# changed by import plugin\\n")\n');
  const modified=await client.callTool({name:'project.validate',arguments:{timeout_ms:60000}});
  expect(modified.isError).toBe(true);
  expect((modified.structuredContent as any).diagnostics.some((d:any)=>d.code==='SNAPSHOT_MODIFIED')).toBe(true);
  expect(await fs.readFile(path.join(root,'main.gd'),'utf8')).toBe('extends AuditBase\n');
 }finally{await client.close();}
},120000);
